---

- block:
  - name: Load alertx variables.
    include_vars: "../defaults/alertx.yml"

  - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file. Airgap.
    include_vars: "airgap/alertx.yml"
    when: is_airgap | default(False)

  - name: Merge alertx asset variables.
    set_fact:
      alertx_assets: "{{ alertx_assets_default | combine(alertx_assets_airgap | default({}), recursive=True) }}"

  - name: Downloading nodejs package
    get_url:
      url: "{{ alertx_assets.noarch_nodejs_repository }}/{{ alertx_assets.gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/alertx/{{ alertx_assets.gui_nodejs }}"

  - name: Unpack nodejs files
    unarchive:
      src: "{{ trix_ood }}/3.0/alertx/{{ alertx_assets.gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/alertx/app/assets/"
      keep_newer: false # override?

  - name: Cleanup nodejs package
    file:
      path: "{{ trix_ood }}/3.0/alertx/{{ alertx_assets.gui_nodejs }}"
      state: absent
  when: not in_image
