---

- block:
  - name: Load DNS variables.
    include_vars: "../defaults/dns.yml"

  - name: Load Airgap DNS variables.
    include_vars: "../vars/airgap/dns.yml"
    when: is_airgap | default(False)

  - name: Merge DNS asset variables.
    set_fact:
      network_assets: "{{ network_assets_default | combine(network_assets_airgap | default({}), recursive=True) }}"

  - name: Downloading DNS nodejs package
    get_url:
      url: "{{ network_assets.noarch_nodejs_repository }}/{{ network_assets.gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/dns/{{ network_assets.gui_nodejs }}"

  - name: Ensure DNS assets directory exists
    ansible.builtin.file:
      path: "{{ trix_ood }}/3.0/dns/app/assets"
      state: directory
      owner: root
      group: root
      mode: "0755"

  - name: Unpack DNS nodejs files
    unarchive:
      src: "{{ trix_ood }}/3.0/dns/{{ network_assets.gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/dns/app/assets/"
      keep_newer: false # override?

  - name: Cleanup DNS nodejs package
    file:
      path: "{{ trix_ood }}/3.0/dns/{{ network_assets.gui_nodejs }}"
      state: absent
  when: not in_image
