---

- block:
  - name: Load Group variables.
    include_vars: "../defaults/group.yml"

  - name: Load Airgap Group variables.
    include_vars: "../vars/airgap/group.yml"
    when: is_airgap | default(False)

  - name: Merge Group asset variables.
    set_fact:
      group_assets: "{{ group_assets_default | combine(group_assets_airgap | default({}), recursive=True) }}"

  - name: Downloading Group nodejs package
    get_url:
      url: "{{ group_assets.noarch_nodejs_repository }}/{{ group_assets.gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/group/{{ group_assets.gui_nodejs }}"

  - name: Ensure Group assets directory exists
    ansible.builtin.file:
      path: "{{ trix_ood }}/3.0/group/app/assets"
      state: directory
      owner: root
      group: root
      mode: "0755"

  - name: Unpack Group nodejs files
    unarchive:
      src: "{{ trix_ood }}/3.0/group/{{ group_assets.gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/group/app/assets/"
      keep_newer: false # override?

  - name: Cleanup Group nodejs package
    file:
      path: "{{ trix_ood }}/3.0/group/{{ group_assets.gui_nodejs }}"
      state: absent
  when: not in_image
