---

- block:
  - name: Load Secrets variables.
    ansible.builtin.include_vars: "../defaults/secrets.yml"

  - name: Load Airgap Secrets variables.
    ansible.builtin.include_vars: "../vars/airgap/secrets.yml"
    when: is_airgap | default(False)

  - name: Merge Secrets asset variables.
    ansible.builtin.set_fact:
      secrets_assets: "{{ secrets_assets_default | combine(secrets_assets_airgap | default({}), recursive=True) }}"

  - name: Downloading Secrets nodejs package
    ansible.builtin.get_url:
      url: "{{ secrets_assets.noarch_nodejs_repository }}/{{ secrets_assets.gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/secrets/{{ secrets_assets.gui_nodejs }}"
      force: true

  - name: Ensure Secrets assets directory exists
    ansible.builtin.file:
      path: "{{ trix_ood }}/3.0/secrets/app/assets"
      state: directory
      owner: root
      group: root
      mode: "0755"

  - name: Unpack Secrets nodejs files
    ansible.builtin.unarchive:
      src: "{{ trix_ood }}/3.0/secrets/{{ secrets_assets.gui_nodejs }}"
      dest: "{{ trix_ood }}/3.0/secrets/app/assets/"
      keep_newer: false

  - name: Cleanup Secrets nodejs package
    ansible.builtin.file:
      path: "{{ trix_ood }}/3.0/secrets/{{ secrets_assets.gui_nodejs }}"
      state: absent
  when: not in_image
