#!/bin/bash

#SBATCH -t 01:00:00
#SBATCH --ntasks=1
#SBATCH -J 'Stage-out'

#Empty scratch dir
if [ -z $jobdir ]; then
    echo "jobdir variable NOT SET failing job"
    exit 1
fi

if [ -z $scratchdir ]; then
    echo "scratchdir variable NOT SET failing job" >&2
    exit 1
fi

concurrentjobs=$(sacctmgr show qos data format=GrpJobs -nP)

#echo "concurrentjobs = $concurrentjobs"
if [ "$concurrentjobs" -ge 1 ]; then
    speedlimit=$(echo "102400/$concurrentjobs"|bc)
    #echo "rsync speed limit is set to $speedlimit"
fi

#echo "rsync -a --delete --remove-source-files --bwlimit=$speedlimit  $scratchdir/* $jobdir/"
rsync -a --delete --remove-source-files --bwlimit=$speedlimit  $scratchdir/* $jobdir/

touch $scratchdir/SLURM_epilogue_postprocess_delete_me_please
