---
# handler file for luna

- name: restart xinetd
  ansible.builtin.systemd:
    name: xinetd
    state: restarted

- name: restart dhcpd
  ansible.builtin.systemd:
    name: dhcpd
    state: restarted

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: restart named
  ansible.builtin.systemd:
    name: named
    state: restarted

- name: restart luna2-daemon
  ansible.builtin.systemd:
    name: luna2-daemon
    state: restarted

- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: fix firewall zones
  shell: "{{ trix_tmpdir }}/fix-firewalld-zones.sh"
  ignore_errors: true
  listen: reload firewalld
