---

group_assets_default:
  noarch_nodejs_repository: "https://updates.clustervision.com/trinityx/{{ trix_version }}/luna-ood-apps/noarch/nodejs/{{ trix_stream }}"
  gui_nodejs: group-1.0.latest.tar.gz
