---
ood_luna_apps_version: 2.0.latest
ood_luna_apps_url: https://updates.clustervision.com/trinityx/{{ trix_version }}/luna2/noarch/pip/{{ trix_stream }}/ood/trinityx-ood-{{ ood_luna_apps_version }}.tar.gz # noqa: yaml[line-length]
ood_apps_admin_group: admins

ood_apps_path: /var/www/ood/apps/sys/

ood_apps_arch_map:
  x86_64: 'amd64'
  aarch64: 'arm64'

ood_apps_arch: "{{ ood_apps_arch_map[system_arch] | default(system_arch) }}"

ood_apps_enabled_default:
  - jupyter
  - codeserver
  - desktop
  - bmcsetup
  - cluster
  - group
  - network
  - node
  - osimage
  - otherdev
  - secrets
  - service
  - switch
  - control
  - users
  - osimagetag
  - monitor
  - dns
  - slurm
  - infiniband
  - rack
  - alertx
  - passwd
  - system-status
  - shell
  - prometheus
  - alertmanager
  - grafana

ood_apps_catalog_default:
  jupyter:
    type: bc
    icon: jupyter.png
    node_rpms:
      - name: [python3.11, python3.11-pip]
    node_apts:
      - name: [python3, python3-pip, python3-venv]

  codeserver:
    type: bc
    icon: code-server.png
    node_rpms:
      - name: "https://github.com/coder/code-server/releases/download/v4.89.0/code-server-4.89.0-{{ ood_apps_arch }}.rpm"
        no_gpgcheck: true
    node_apts:
      - name: "https://github.com/coder/code-server/releases/download/v4.89.0/code-server_4.89.0_{{ ood_apps_arch }}.deb"

  desktop:
    override: true
    type: bc
    icon: desktop.png
    props:
      idle_timeout: 3600
      desktops:
        - xfce
      desktops_default: xfce
    node_rpms:
      - name: https://yum.osc.edu/ondemand/4.1/ondemand-release-compute-4.1-1.el{{ ansible_distribution_major_version }}.noarch.rpm
        no_gpgcheck: true
      - name: ["turbovnc", "python3-websockify", "dbus-x11", "@xfce"]
        enablerepo: crb
    tasks: ["desktop.yml"]

  bmcsetup:
    type: trinity
    icon: bmc-setup.png
    mode: "0750"
  cluster:
    type: trinity
    icon: cluster.png
    mode: "0750"
  group:
    type: trinity
    icon: groups.png
    mode: "0750"
    tasks: ["group.yml"]
  network:
    type: trinity
    icon: network.png
    mode: "0750"
  node:
    type: trinity
    icon: nodes.png
    mode: "0750"
    # tasks: ["node.yml"] #TODO: Until Node App finished, this is commented out to avoid confusion
  osimage:
    type: trinity
    icon: os-images.png
    mode: "0750"
  otherdev:
    type: trinity
    icon: other-devices.png
    mode: "0750"
  secrets:
    type: trinity
    icon: secrets.png
    mode: "0750"
  service:
    type: trinity
    icon: service.png
    mode: "0750"
  switch:
    type: trinity
    icon: switch.png
    mode: "0750"
  control:
    type: trinity
    icon: control.png
    mode: "0750"
  users:
    type: trinity
    icon: users.png
    mode: "0750"
  osimagetag:
    type: trinity
    icon: os-images-tags.png
    mode: "0750"
  monitor:
    type: trinity
    icon: monitoring.png
    mode: "0750"
  dns:
    type: trinity
    icon: dns.png
    mode: "0750"
  slurm:
    type: trinity
    icon: slurm.png
    mode: "0750"
  infiniband:
    type: trinity
    icon: infiniband.png
    mode: "0750"
    tasks: ["infiniband.yml"]
  rack:
    type: trinity
    icon: rack.png
    mode: "0750"
    tasks: ["rack.yml"]
  alertx:
    type: trinity
    icon: alertx.png
    mode: "0750"
    tasks: ["alertx.yml"]
  passwd:
    type: trinity
    icon: passwd.png
    mode: "0755"
    tasks: ["passwd.yml"]
  system-status:
    mode: "0000"
  shell:
    icon: shell.png
    override: true
    mode: "0750"
    props:
      lchroot_wrapper_path: /usr/local/sbin/ood_lchroot_wrapper
    tasks: ["lchroot.yml"]
  prometheus:
    icon: prometheus.png
  alertmanager:
    icon: alert-manager.png
    mode: "0750"
  grafana:
    icon: grafana.png

ood_apps_overrides_os: {}
ood_apps_overrides_airgap: {}
ood_apps_overrides: {}
