# OpenHPC repositories. commonly used for openhpc and schedulers

# --- for EL8:
el8_openhpc_repositories:
  - name: base
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/OpenHPC/2/EL_8/
    gpgcheck: false
  - name: updates
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/OpenHPC/2/update.2.9.1/EL_8/
    gpgcheck: false

# --- for EL9:
el9_openhpc_repositories:
  - name: base
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/OpenHPC/3/EL_9/
    gpgcheck: false
  - name: updates
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/OpenHPC/3/update.3.3.1/EL_9/
    gpgcheck: false

# --- for EL10:
el10_openhpc_repositories:
  - name: base
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/OpenHPC/4/EL_10/
    gpgcheck: false
