---

luna2_noarch_pip_repository: "https://{{ ag_server }}/{{ ag_repo }}/trinityx/{{ trix_version }}/luna2/noarch/pip/{{ trix_stream }}"

luna2_aarch64_ipxe_files: "https://{{ ag_server }}/{{ ag_repo }}/trinityx/{{ trix_version }}/additional/aarch64/ipxe"
luna2_x86_64_ipxe_files: "https://{{ ag_server }}/{{ ag_repo }}/trinityx/{{ trix_version }}/additional/x86_64/ipxe"

