{
 "title": "TrinityX - IPMI Environmentals",
 "tags": [
  "statistics",
  "ipmi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU temperatures",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "($tag_host) $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE (\"name\" =~ /^cpu[0-9]*_temp$/ ) AND $timeFilter GROUP BY time($__interval), \"host\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": " /^cpu[0-9]*_temp$/" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname[.]?/" }
     ]
    }
   ]
  },
  {
   "title": "System / Air Inlet Templerature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "($tag_host) $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE (\"name\" = 'system_temp' OR \"name\" = 'inlet_air_temp') AND $timeFilter GROUP BY time($__interval), \"host\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^system_temp|inlet_air_temp$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname[.]?/" }
     ]
    }
   ]
  },
  {
   "title": "DIMM temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "($tag_host) $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/dimm/" },
      { "condition": "AND", "key": "unit", "operator": "=", "value": "degrees_c" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname[.]?/" }
     ]
    }
   ]
  },
  {
   "title": "HDD temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "($tag_host) $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE (\"name\" =~ /^hdd[0-9]*_temp$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^hdd.*_temp/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname[.]?/" }
     ]
    }
   ]
  },
  {
   "title": "Fan speeds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "($tag_host) $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "SELECT mean(\"value\") FROM \"ipmi_sensor\" WHERE (\"name\" =~ /fan/ AND \"host\" =~  /^$hostname[.]?\\$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"name\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/fan/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname[.]?/" }
     ]
    }
   ]
  }
 ]
}