{
 "title": "Home",
 "tags": [ "home" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "System status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"/public/triX_7.png\" width=\"auto\" height=\"100%\" />"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": {
    "content": "The webportal for users is available on port 8080.\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Alerts",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TrinityX Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_load1 * 100", "legendFormat": "__auto" },
    { "expr": "node_load5 * 100", "legendFormat": "__auto" },
    { "expr": "node_load15 * 100", "legendFormat": "__auto" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "__auto" },
    {
     "expr": "(1-(avg_over_time(node_memory_MemAvailable_bytes[$__rate_interval]) / avg_over_time(node_memory_MemTotal_bytes[$__rate_interval])))*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1-(avg_over_time(node_memory_SwapFree_bytes[$__rate_interval]) / avg_over_time(node_memory_SwapTotal_bytes[$__rate_interval])))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Controller Local filesystems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=~\"ext4\", luna_group=\"controller\", mountpoint!~\"/var/.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4\", luna_group=\"controller\", mountpoint!~\"/var/.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"ext4\", luna_group=\"controller\", mountpoint!~\"/var/.*\"}-node_filesystem_free_bytes{fstype=~\"ext4\", luna_group=\"controller\", mountpoint!~\"/var/.*\"})/node_filesystem_size_bytes{fstype=~\"ext4\", luna_group=\"controller\", mountpoint!~\"/var/.*\"}*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Controller Remote filesystems",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=~\"nfs\", luna_group=\"controller\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"nfs\", luna_group=\"controller\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"nfs\", luna_group=\"controller\"}-node_filesystem_free_bytes{fstype=~\"nfs\", luna_group=\"controller\"})/node_filesystem_size_bytes{fstype=~\"nfs\", luna_group=\"controller\"}*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}