---
- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file. Airgap.
  include_vars: "{{ item }}"
  with_first_found:
    - "airgap/{{ ansible_distribution }}{{ ansible_distribution_major_version}}.yaml"
    - "airgap/{{ ansible_os_family }}{{ ansible_distribution_major_version}}.yaml"
    - "airgap/{{ ansible_distribution }}.yaml"
    - "airgap/{{ ansible_os_family }}.yaml"
    - "airgap/main.yaml"
  no_log: true
  ignore_errors: true
  when: is_airgap | default(False)

- name: Install luna2 packages
  yum:
    name: '{{ luna2_packages }}'
    state: present
    enablerepo: luna2
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"

# Install config_manager pip package inside the Luna2 virtualenv
- name: Install config_manager pip package
  ansible.builtin.pip:
    name: '{{config_manager_noarch_pip_repository}}/config-manager/{{ config_manager_wheel }}'
    virtualenv: '{{ trix_local }}/python' 
    extra_args: "--upgrade"

# Symlink '{{ trix_local }}/python/bin/trix-config-manager' to '{{ trix_local }}/sbin/trix-config-manager'
- name: Symlink '{{ trix_local }}/python/bin/trix-config-manager' to '{{ trix_local }}/sbin/trix-config-manager'
  ansible.builtin.file:
    src: '{{ trix_local }}/python/bin/trix-config-manager'
    dest: '{{ trix_local }}/sbin/trix-config-manager'
    state: link

# --- taken care off by config-slurm role
# Add the managed block to the managed files
#- name: Fix structure of managed files
#  include_tasks: managed_block.yml
#  loop: "{{ scripts_managed_files }}"
  
