---

ood_apps_overrides_os:
  jupyter:
    node_rpms:
      - name: [python3.13, python3.13-pip]

  desktop:
    props:
      desktops:
        - kde
      desktops_default: kde
    node_rpms:
      - name: https://yum.osc.edu/ondemand/4.1/ondemand-release-compute-4.1-1.el{{ ansible_distribution_major_version }}.noarch.rpm
        no_gpgcheck: true
      - name: ["turbovnc", "python3-websockify", "dbus-x11", "@KDE"]
        enablerepo: crb
