---

ood_apps_overrides:
  codeserver:
    node_rpms:
      - name: "https://{{ ag_server }}/{{ ag_repo }}/rpms/coder/code-server/releases/download/v4.89.0/code-server-4.89.0-{{ ood_apps_arch }}.rpm"
        no_gpgcheck: true
    node_apts:
      - name: "https://{{ ag_server }}/{{ ag_repo }}/rpms/coder/code-server/releases/download/v4.89.0/code-server_4.89.0_{{ ood_apps_arch }}.deb"

  desktop:
    node_repositories:
      - name: ondemand-compute
        repo: "https://{{ ag_server }}/{{ ag_repo }}/repos/ondemand-compute"
        gpgcheck: False
    node_rpms:
      - name: ["turbovnc", "python3-websockify", "dbus-x11", "@xfce"]
        enablerepo: crb

ood_apps_remove:
  rack:
    - tasks

ood_apps_meta:
  ood_luna_apps_url: https://{{ ag_server }}/{{ ag_repo }}/trinityx/{{ trix_version }}/luna2/noarch/pip/{{ trix_stream }}/ood/trinityx-ood-{{ ood_luna_apps_version }}.tar.gz # noqa: yaml[line-length]
