---

ood_apps_overrides:
  jupyter:
    node_rpms:
      - name: [python3.13, python3.13-pip]

  desktop:
    props:
      desktops:
        - kde
      desktops_default: kde
    node_repositories:
      - name: ondemand-compute
        repo: https://{{ ag_server }}/{{ ag_repo }}/repos/ondemand-compute
        gpgcheck: False
    node_rpms:
      - name: ["turbovnc", "python3-websockify", "dbus-x11", "@KDE"]
        enablerepo: crb

ood_apps_remove:
  group:
    - tasks
  rack:
    - tasks

ood_apps_meta:
  ood_luna_apps_url: https://{{ ag_server }}/{{ ag_repo }}/trinityx/{{ trix_version }}/luna2/noarch/pip/{{ trix_stream }}/ood/trinityx-ood-{{ ood_luna_apps_version }}.tar.gz # noqa: yaml[line-length]
