---
- name: Set on_node variable
  set_fact:
    on_node: '{{ True if not in_image else False }}'
  tags: always

- debug:
    msg: "in_image: {{ in_image }}, in_login_image: {{ in_login_image|default(False) }}, on_node: {{ on_node }}"
  tags: always

- block:
  - name: Set airgap distribution repo
    set_fact:
      ag_repo: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"

  - debug:
      msg: "Airgap repo location: {{ ag_repo }}"
  when: is_airgap | default(False)
  tags: always
