---

package_based_repositories: {}
use_baseurl_repositories: []
custom_repositories: {}

trinityx_repositories:
  - name: epel
    repo: https://{{ ag_server }}/repos/epel
    gpgcheck: False
  - name: trix
    repo: https://{{ ag_server }}/trinityx/{{ trix_version }}/os/{{ hostvars[inventory_hostname].ansible_distribution|lower }}/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/{{ system_arch }}
    gpgcheck: False
  - name: luna2
    repo: https://{{ ag_server }}/trinityx/{{ trix_version }}/luna2/{{ hostvars[inventory_hostname].ansible_distribution|lower }}/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/{{ system_arch }}
    gpgcheck: False
  - name: luna2-noarch
    repo: https://{{ ag_server }}/trinityx/{{ trix_version }}/luna2/noarch/rpms
    gpgcheck: False
  - name: elrepo
    repo: https://{{ ag_server }}/repos/elrepo
    gpgcheck: False
    enabled: False
  - name: elrepo-testing
    repo: https://{{ ag_server }}/repos/elrepo-testing
    gpgcheck: False
    enabled: False
  - name: elrepo-kernel
    repo: https://{{ ag_server }}/repos/elrepo-kernel
    gpgcheck: False
    enabled: False
  - name: elrepo-extras
    repo: https://{{ ag_server }}/repos/elrepo-extras
    gpgcheck: False
    enabled: False

external_repository_rpms: []
