---

external_repository_rpms:
  - name: https://{{ trix_ctrl_ip }}/trinityx/{{ trix_version }}/additional/noarch/rpms/elrepo-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.el{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.elrepo.noarch.rpm
    no_gpgcheck: True
  - name: https://{{ trix_ctrl_ip }}/rpms/epel-release-latest-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.noarch.rpm
    no_gpgcheck: True


package_based_repositories: {}
