---
# defaults file for pdsh

trinityx_pdsh_version: "2.36"
trinityx_pdsh_repo_baseurl: https://updates.clustervision.com/cv-pdsh
trinityx_pdsh_arch: "{{ system_arch | default(ansible_architecture) }}"
trinityx_pdsh_genders_conf_path: "{{ trix_shared }}/etc"
trinityx_pdsh_genders_group: "{{ admin_group | default('root') }}"

trinityx_pdsh_repositories:
  - name: RedHat
    repo: "{{ trinityx_pdsh_repo_baseurl }}/el/{{ ansible_distribution_major_version }}/{{ trinityx_pdsh_version }}/{{ trinityx_pdsh_arch }}"
    gpgcheck: false

trinityx_pdsh_packages:
  - pdsh-cv
  - pdsh-cv-rcmd-ssh
  - pdsh-cv-rcmd-exec
  - pdsh-cv-mod-machines
  - pdsh-cv-mod-netgroup
  - pdsh-cv-mod-genders

trinityx_pdsh_conflicting_packages:
  - pdsh-ohpc
  - pdsh-mod-genders-ohpc
  - pdsh-mod-dshgroup-ohpc
  - pdsh-mod-slurm-ohpc
  - pdsh
  - pdsh-rcmd-exec
  - pdsh-rcmd-rsh
  - pdsh-rcmd-ssh
  - pdsh-mod-dshgroup
  - pdsh-mod-genders
  - pdsh-mod-machines
  - pdsh-mod-netgroup
  - pdsh-mod-nodeupdown
  - pdsh-mod-torque