#!/bin/sh

# We redefine the following function to make sure that dhclient will not
# overwrite our resolv.conf, regardless of the configuration of the interfaces.
# See man 8 dhclient-script for more details about the function.

make_resolv_conf() {
    :
}

