{
 "title": "PJS",
 "tags": [
  "dashboard",
  "slurm",
  "system"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job_state",
    "label": "Job State",
    "query": {
     "query": "label_values(slurm_job_info_latest,jobstate)"
    }
   },
   {
    "name": "job_id",
    "label": "Job ID",
    "query": {
     "query": "label_values(slurm_job_info{jobstate=~\"$job_state\"},jobid)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Jobs Overview",
   "type": "table",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "slurm_job_info{jobid=~\"^($job_id)$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "slurm_job_allocated_cores{jobid=~\"^($job_id)$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "slurm_job_allocated_memory{jobid=~\"^($job_id)$\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "slurm_job_allocated_gres{jobid=~\"^($job_id)$\", gres_type=\"gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs Overview",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "slurm_job_info{jobid=~\"^($job_id)$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Job Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Energy Consumption",
   "type": "stat",
   "description": "Energy consumption of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(\r\n        sum by (hostname) (avg_over_time(power_consumption_per_cpu_watts[$__range:]))\r\n        * \r\n        sum by (hostname) (\r\n            last_over_time(\r\n                (\r\n                    max without (instance) (slurm_job_allocated_cores{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"}) \r\n                    * on (jobid) group_left \r\n                    max by (jobid) (slurm_job_runtime{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})\r\n                )\r\n                [$__range:]))\r\n) / 3600\r\n+\r\n(sum(\r\n        sum by (hostname) (avg_over_time(power_consumption_per_gpu_watts[$__range:]))\r\n        * \r\n        sum by (hostname) (\r\n            last_over_time(\r\n                (\r\n                    max without (instance) (slurm_job_allocated_gres{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\",gres_type=\"gpu\"}) \r\n                    * on (jobid) group_left \r\n                    max by (jobid) (slurm_job_runtime{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})\r\n                )\r\n                [$__range:]))\r\n) OR vector(0)) / 3600) * max(slurm_job_info{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})",
     "legendFormat": "energy_allocated"
    },
    {
     "expr": "(sum(\r\n        sum by (hostname) (avg_over_time(power_consumption_per_cpu_watts[$__range:]))\r\n        * \r\n        sum by (hostname) (last_over_time(slurm_job_total_cpu_seconds_total{jobid=~\"^($job_id)$\"}[$__range:]))\r\n) / 3600)* max(slurm_job_info{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})",
     "legendFormat": "energy_cpu_usage"
    },
    {
     "expr": "(sum(\r\n        sum by (hostname) (avg_over_time(power_consumption_per_gpu_watts[$__range:]))\r\n        * \r\n        sum by (hostname) (last_over_time(slurm_job_gpu_streaming_multiprocessor_seconds_total{jobid=~\"^($job_id)$\"}[$__range:]))\r\n) / 3600)* max(slurm_job_info{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})\r\n",
     "legendFormat": "energy_gpu_usage"
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "timeseries",
   "description": "Power consumption of the SLURM jobs over time ",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "(sum(\r\n        sum by (hostname) (avg_over_time(power_consumption_per_cpu_watts[$__range:]))\r\n        * \r\n        sum by (hostname) (\r\n            last_over_time(\r\n                (\r\n                    max without (instance) (slurm_job_allocated_cores{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"}) \r\n                    * on (jobid) group_left \r\n                    max by (jobid) (slurm_job_runtime{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})\r\n                )\r\n                [$__range:]))\r\n) / 3600\r\n+\r\n(sum(\r\n        sum by (hostname) (avg_over_time(power_consumption_per_gpu_watts[$__range:]))\r\n        * \r\n        sum by (hostname) (\r\n            last_over_time(\r\n                (\r\n                    max without (instance) (slurm_job_allocated_gres{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\",gres_type=\"gpu\"}) \r\n                    * on (jobid) group_left \r\n                    max by (jobid) (slurm_job_runtime{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})\r\n                )\r\n                [$__range:]))\r\n) OR vector(0)) / 3600) * max(slurm_job_info{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})",
     "legendFormat": "energy_allocated"
    },
    {
     "expr": "(sum(\r\n        sum by (hostname) (avg_over_time(power_consumption_per_cpu_watts[$__range:]))\r\n        * \r\n        sum by (hostname) (last_over_time(slurm_job_total_cpu_seconds_total{jobid=~\"^($job_id)$\"}[$__range:]))\r\n) / 3600)* max(slurm_job_info{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})",
     "legendFormat": "energy_cpu_usage"
    },
    {
     "expr": "(sum(\r\n        sum by (hostname) (avg_over_time(power_consumption_per_gpu_watts[$__range:]))\r\n        * \r\n        sum by (hostname) (last_over_time(slurm_job_gpu_streaming_multiprocessor_seconds_total{jobid=~\"^($job_id)$\"}[$__range:]))\r\n) / 3600)* max(slurm_job_info{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"})\r\n",
     "legendFormat": "energy_gpu_usage"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "description": "Mean Power consumption of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\nsum(\r\n    sum by (hostname) (power_consumption_per_cpu_watts)\r\n    *\r\n    sum by (hostname) (slurm_job_allocated_cores{jobid=~\"^($job_id)$\", jobstate=\"RUNNING\"})\r\n    )\r\n+\r\n(sum(\r\n    sum by (hostname)(power_consumption_per_gpu_watts)\r\n    *\r\n    sum by (hostname) (slurm_job_allocated_gres{jobid=~\"^($job_id)$\", jobstate=\"RUNNING\", gres_type=\"gpu\"})\r\n    ) OR vector(0))\r\n)",
     "legendFormat": "power_allocated"
    },
    {
     "expr": "sum(\r\n    sum by (hostname) (power_consumption_per_cpu_watts)\r\n    *\r\n    sum by (hostname) (rate(slurm_job_total_cpu_seconds_total{jobid=~\"^($job_id)$\"}[$__rate_interval:]) )\r\n    )",
     "legendFormat": "power_cpu_usage"
    },
    {
     "expr": "sum(\r\n    sum by (hostname) (power_consumption_per_gpu_watts)\r\n    *\r\n    sum by (hostname)((max without (instance) (slurm_job_gpu_streaming_multiprocessor_usage > 0)) * on (jobid) group_left \r\n                    max by (jobid) (slurm_job_info{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"}))\r\n    )",
     "legendFormat": "power_gpu_usage"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "description": "Power consumption of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(\r\nsum(\r\n    sum by (hostname) (power_consumption_per_cpu_watts)\r\n    *\r\n    sum by (hostname) (slurm_job_allocated_cores{jobid=~\"^($job_id)$\", jobstate=\"RUNNING\"})\r\n    )\r\n+\r\n(sum(\r\n    sum by (hostname)(power_consumption_per_gpu_watts)\r\n    *\r\n    sum by (hostname) (slurm_job_allocated_gres{jobid=~\"^($job_id)$\", jobstate=\"RUNNING\", gres_type=\"gpu\"})\r\n    ) OR vector(0))\r\n)",
     "legendFormat": "power_allocated"
    },
    {
     "expr": "sum(\r\n    sum by (hostname) (power_consumption_per_cpu_watts)\r\n    *\r\n    sum by (hostname) (rate(slurm_job_total_cpu_seconds_total{jobid=~\"^($job_id)$\"}[$__rate_interval:]) )\r\n    )",
     "legendFormat": "power_cpu_usage"
    },
    {
     "expr": "sum(\r\n    sum by (hostname) (power_consumption_per_gpu_watts)\r\n    *\r\n    sum by (hostname)((max without (instance) (slurm_job_gpu_streaming_multiprocessor_usage > 0)) * on (jobid) group_left \r\n                    max by (jobid) (slurm_job_info{jobid=~\"^($job_id)$\",jobstate=\"RUNNING\"}))\r\n    )",
     "legendFormat": "power_gpu_usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Mean CPU usage of the SLURM jobs",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg by(jobid,hostname) (slurm_job_allocated_cores{jobid=~\"^($job_id)$\", jobstate=\"RUNNING\"})) ",
     "legendFormat": "cpu_allocated"
    },
    {
     "expr": "sum(rate(slurm_job_total_cpu_seconds_total{jobid=~\"^($job_id)$\"}[$__rate_interval:])  ) ",
     "legendFormat": "cpu_usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Current CPU usage of the SLURM jobs",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 28 },
   "targets": [
    {
     "expr": "sum(avg by(jobid,hostname) (slurm_job_allocated_cores{jobid=~\"^($job_id)$\", jobstate=\"RUNNING\"})) ",
     "legendFormat": "cpu_allocated"
    },
    {
     "expr": "sum(rate(slurm_job_user_cpu_seconds_total{jobid=~\"^($job_id)$\"}[$__rate_interval:])  ) ",
     "legendFormat": "cpu_usage_user"
    },
    {
     "expr": "sum(rate(slurm_job_system_cpu_seconds_total{jobid=~\"^($job_id)$\"}[$__rate_interval:])  )",
     "legendFormat": "cpu_usage_system"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Mean  Memory usage of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(slurm_job_allocated_memory{jobid=~\"${job_id}\", jobstate=\"RUNNING\"} > 0)",
     "legendFormat": "memory_allocated"
    },
    {
     "expr": "sum(slurm_job_memory_bytes{jobid=~\"${job_id}\"})",
     "legendFormat": "memory_usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory usage of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(slurm_job_memory_bytes{jobid=~\"${job_id}\"})",
     "legendFormat": "memory_usage"
    },
    {
     "expr": "sum(slurm_job_allocated_memory{jobid=~\"${job_id}\", jobstate=\"RUNNING\"} ) > 0",
     "legendFormat": "memory_allocated"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "stat",
   "description": "Mean GPU usage of the SLURM jobs",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (slurm_job_allocated_gres{jobid=~\"^($job_id)$\", jobstate=\"RUNNING\", gres_type=\"gpu\"})",
     "legendFormat": "gpu_allocated"
    },
    {
     "expr": "sum(\r\n  rate(\r\n    label_replace(\r\n      {__name__=~\"slurm_job_gpu_.*_seconds_total\", jobid=~\"^($job_id)$\"},\r\n      \"metric\", \"$1\", \"__name__\", \"(.*)\"\r\n    )[$__rate_interval:]\r\n  )\r\n)",
     "legendFormat": "gpu_usage"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "description": "GPU usage of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 42 },
   "targets": [
    {
     "expr": "sum (slurm_job_allocated_gres{jobid=~\"^($job_id)$\", jobstate=\"RUNNING\", gres_type=\"gpu\"})",
     "legendFormat": "gpu_allocated"
    },
    {
     "expr": "sum(\r\n  rate(\r\n    label_replace(\r\n      {__name__=~\"slurm_job_gpu_.*_seconds_total\", jobid=~\"^($job_id)$\"},\r\n      \"metric\", \"$1\", \"__name__\", \"(.*)\"\r\n    )[$__rate_interval:]\r\n  )\r\n)",
     "legendFormat": "gpu_usage"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "stat",
   "description": "Mean GPU memory usage of the SLURM jobs",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=~\"slurm_job_gpu_.*_mem_bytes\", jobid=~\"^($job_id)$\"}>0)\r\n",
     "legendFormat": "gpu_memory_usage"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "description": "GPU Memory usage of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum ({__name__=~\"slurm_job_gpu_.*_mem_bytes\", jobid=~\"^($job_id)$\"}>0)\r\n",
     "legendFormat": "gpu_memory_usage"
    }
   ]
  },
  {
   "title": "Reads / Writes (IOps)",
   "type": "timeseries",
   "description": "Reads / Writes of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(slurm_job_reads{jobid=~\"^($job_id)$\"}[$__rate_interval:]) )",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(slurm_job_writes{jobid=~\"^($job_id)$\"}[$__rate_interval:]) )",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Reads / Writes (Bytes)",
   "type": "timeseries",
   "description": "Bytes Read / Written of the SLURM jobs over time",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(slurm_job_read_bytes{jobid=~\"^($job_id)$\"}[$__rate_interval:])  )",
     "legendFormat": "bytes_read"
    },
    {
     "expr": "sum(rate(slurm_job_write_bytes{jobid=~\"^($job_id)$\"}[$__rate_interval:]))",
     "legendFormat": "bytes_written"
    },
    {
     "expr": "sum(rate(slurm_job_cancelled_write_bytes{jobid=~\"^($job_id)$\"}[$__rate_interval:]) )",
     "legendFormat": "bytes_write_fail"
    }
   ]
  }
 ]
}