{
 "title": "TrinityX - Workload management",
 "tags": [
  "statistics",
  "slurm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "partition",
    "query": "SHOW TAG VALUES WITH KEY = \"partition\""
   }
  ]
 },
 "panels": [
  {
   "title": "Quickstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "resources",
     "query": "select count(distinct(\"partition\")) from (select \"cpus\", \"partition\" from system)",
     "select": [
      [
       { "params": [ "_partition" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "partitions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "resources",
     "query": "SELECT count(distinct(\"_hostname\")) FROM \"resources\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "_hostname" ], "type": "field" },
       { "params": [ "allocated_hostnames" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    },
    {
     "measurement": "resources",
     "query": "SELECT count(distinct(\"_hostname\")) FROM \"resources\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "_hostname" ], "type": "field" },
       { "params": [ "total_hostnames" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Allocations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "resources",
     "query": "SELECT count(distinct(\"_hostname\")) FROM \"resources\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "_hostname" ], "type": "field" },
       { "params": [ "allocated_hostnames" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" },
      { "condition": "AND", "key": "state::tag", "operator": "=", "value": "allocated" }
     ]
    },
    {
     "measurement": "resources",
     "query": "SELECT count(distinct(\"_hostname\")) FROM \"resources\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "_hostname" ], "type": "field" },
       { "params": [ "total_hostnames" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::field" ], "type": "tag" }
     ],
     "measurement": "resources",
     "query": "SELECT last(\"cpus\") FROM \"system\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY \"partition\"::tag",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocated CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::field" ], "type": "tag" }
     ],
     "measurement": "resources",
     "query": "SELECT last(\"cpus\") FROM \"system\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY \"partition\"::tag",
     "select": [
      [
       { "params": [ "alloc_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::field" ], "type": "tag" }
     ],
     "measurement": "resources",
     "query": "SELECT last(\"cpus\") FROM \"system\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY \"partition\"::tag",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::field" ], "type": "tag" }
     ],
     "measurement": "resources",
     "query": "SELECT last(\"cpus\") FROM \"system\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY \"partition\"::tag",
     "select": [
      [
       { "params": [ "alloc_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Allocations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Allocated Nodes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "resources",
     "query": "SELECT count(distinct(\"_hostname\")) FROM \"resources\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "_hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" },
      { "condition": "AND", "key": "state::tag", "operator": "=", "value": "allocated" }
     ]
    },
    {
     "alias": "Total Nodes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "resources",
     "query": "SELECT count(distinct(\"_hostname\")) FROM \"resources\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "_hostname" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "resources",
     "query": "SELECT \"cpus\", \"alloc_cpus\" FROM \"resources\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY \"hostname\"::tag",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" }
      ],
      [
       { "params": [ "alloc_cpus" ], "type": "field" }
      ],
      [
       { "params": [ "_hostname" ], "type": "field" }
      ],
      [
       { "params": [ "_partition" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "measurement": "resources",
     "query": "SELECT \"cpus\", \"alloc_cpus\" FROM \"resources\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY \"hostname\"::tag",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" }
      ],
      [
       { "params": [ "alloc_memory" ], "type": "field" }
      ],
      [
       { "params": [ "_hostname" ], "type": "field" }
      ],
      [
       { "params": [ "_partition" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Partition statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Pending jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT count(distinct(\"_job_id\")) FROM \"jobs\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval), \"state\"::tag",
     "select": [
      [
       { "params": [ "_job_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" },
      { "condition": "AND", "key": "state::tag", "operator": "=", "value": "pending" }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "state::tag" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "query": "SELECT count(distinct(\"_job_id\")) FROM \"jobs\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval), \"state\"::tag",
     "select": [
      [
       { "params": [ "_job_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Running jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT count(distinct(\"_job_id\")) FROM \"jobs\" WHERE (\"partition\"::tag =~ /^$partition$/) AND $timeFilter GROUP BY time($interval), \"state\"::tag",
     "select": [
      [
       { "params": [ "_job_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "partition::tag", "operator": "=~", "value": "/^$partition$/" },
      { "condition": "AND", "key": "state::tag", "operator": "=~", "value": "/completing|running/" }
     ]
    }
   ]
  },
  {
   "title": "Accounting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Time per job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Job($tag_job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPUTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage per job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "Job($tag_job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPUUtilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSS per job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Job($tag_job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RSS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM size per job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Job($tag_job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VMSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ReadMB per job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "Job($tag_job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ReadMB",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WriteMB per job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "Job($tag_job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "job" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WriteMB",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}