{
 "title": "Home",
 "tags": [ "home" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "alertmanager_datasource",
    "label": "Alertmanager Datasource",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   },
   { "name": "luna_group", "label": "Luna Group", "query": { "query": "label_values(up,luna_group)" } },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(up{luna_group=~\"$luna_group\"},hostname)"
    }
   },
   { "name": "severity", "label": "Alert Severity", "query": { "query": "label_values(ALERTS,severity)" } }
  ]
 },
 "panels": [
  {
   "title": "System status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"/public/triX.png\" width=\"auto\" height=\"100%\" />"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "description": "Quick glance of how many nodes are up and running",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max  (ha_cluster_pacemaker_fail_count)",
     "legendFormat": "HA Status"
    },
    {
     "expr": "sum(max by(hostname) (up{exporter!=\"prometheus\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"}))",
     "legendFormat": "Up"
    },
    {
     "expr": "sum(max by(hostname) (up{exporter!=\"prometheus\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"}))/count(avg by(hostname) (up{exporter!=\"prometheus\",luna_group=~\"$luna_group\", hostname=~\"$hostname\"}))",
     "legendFormat": "Up "
    },
    {
     "expr": "count(max by(hostname) (up{exporter!=\"prometheus\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"}))",
     "legendFormat": "Max Up"
    },
    {
     "expr": "count(max by(hostname) (up{exporter!=\"prometheus\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"}))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Controller Filesystems",
   "type": "table",
   "description": "List and statistics of detected filesystems ",
   "gridPos": { "h": 11, "w": 12, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"} > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_filesystem_size_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}-node_filesystem_free_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"})/node_filesystem_size_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}*100  > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "description": "Quick glance of alerts firing on the nodes",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "filters": "hostname=~\"$hostname\",luna_group=~\"$luna_group\",severity=~\"$severity\""
    }
   ]
  },
  {
   "title": "Resources",
   "type": "stat",
   "description": "Quick glance of the total resources on the nodes",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\",luna_group=~\"$luna_group\", hostname=~\"$hostname\"}))",
     "legendFormat": "Cores"
    },
    {
     "expr": "sum by (name) (nvidia_smi_gpu_info{luna_group=~\"$luna_group\", hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "table",
   "description": "Summary of all the nodes statisics",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(node_load1{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}/count(node_cpu_seconds_total{mode=\"idle\",luna_group=~\"$luna_group\", hostname=~\"$hostname\"}) without (cpu,mode)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_load5{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}/count(node_cpu_seconds_total{mode=\"idle\",luna_group=~\"$luna_group\", hostname=~\"$hostname\"}) without (cpu,mode)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_load15{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}/count(node_cpu_seconds_total{mode=\"idle\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"}) without (cpu,mode)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"} - node_memory_MemFree_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"} - node_memory_Cached_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"} - node_memory_Buffers_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"})/node_memory_MemTotal_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"} - node_memory_SwapFree_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"})/node_memory_SwapTotal_bytes{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"}) without (cpu,mode)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (hostname, luna_group) (ipmi_temperature_celsius{ name=~\"[cC][pP][uU].*[tT][eE][mM][pP].*\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (hostname, luna_group) (node_systemd_unit_state{state=\"failed\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (hostname, luna_group) (nvidia_smi_gpu_info{luna_group=~\"$luna_group\", hostname=~\"$hostname\"}) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (hostname, luna_group) (nvidia_smi_temperature_gpu{luna_group=~\"$luna_group\", hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (hostname, luna_group) (ipmi_temperature_celsius{ name=~\"S[Yy][Ss].*[tT][eE][mM][pP].*\", luna_group=~\"$luna_group\", hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    },
    {
     "filters": "hostname=~\"$hostname\",luna_group=~\"$luna_group\",severity=~\"$severity\",exporter!=\"prometheus\""
    },
    {
     "expr": "max by (hostname, luna_group)  (ipmi_dcmi_power_consumption_watts{luna_group=~\"$luna_group\", hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}