{
 "title": "ZFS",
 "tags": [
  "zfs",
  "filesystem",
  "dashboard"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "luna_group", "label": "Luna Group", "query": { "query": "label_values(up,luna_group)" } },
   {
    "name": "hostname",
    "label": "Luna Group",
    "query": {
     "query": "label_values(up{luna_group=~\"$luna_group\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Stats", "type": "row", "description": "General Stats", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zpool State",
   "type": "stat",
   "description": "Zpool State",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "clamp( max(node_zfs_zpool_state{luna_group=\"$luna_group\", hostname=\"$hostname\", state=\"online\"} ),0 ,1) * 2",
     "legendFormat": "Online"
    },
    {
     "expr": "clamp( max(node_zfs_zpool_state{luna_group=\"$luna_group\", hostname=\"$hostname\", state!=\"online\"} ),0 ,1)",
     "legendFormat": "Faulty"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "stat",
   "description": "Total Size",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Used",
   "type": "stat",
   "description": "Total Used",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"} - node_filesystem_free_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"})",
     "legendFormat": "Total used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Total Allocated/Free",
   "type": "piechart",
   "description": "Total Allocated/Free",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"} - node_filesystem_free_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Total pool usage",
   "type": "timeseries",
   "description": "Total pool usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"} - node_filesystem_free_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"})\r\n",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"})",
     "legendFormat": "size"
    },
    {
     "expr": "sum(node_filesystem_free_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "ZFS filesystems size",
   "type": "stat",
   "description": "ZFS filesystems size",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "ZFS filesystems free",
   "type": "stat",
   "description": "ZFS filesystems free",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"}",
     "legendFormat": "{{ mountpoint }}"
    },
    {
     "expr": "node_filesystem_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\", fstype=\"zfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Pool Activity",
   "type": "timeseries",
   "description": "Pool Activity",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_dataset_nread{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "sum(rate(node_zfs_zpool_dataset_nwritten{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "Write Bytes"
    },
    {
     "expr": "sum(rate(node_zfs_zpool_dataset_reads{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "Read Ops"
    },
    {
     "expr": "sum(rate(node_zfs_zpool_dataset_writes{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "Write Ops"
    }
   ]
  },
  {
   "title": "ZFS Pool details",
   "type": "table",
   "description": "ZFS Pool details",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "node_zfs_zpool_state{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Zpool", "type": "row", "description": "Zpool", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Dataset Read Operations Rate",
   "type": "timeseries",
   "description": "Dataset Read Operations Rate",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_dataset_reads{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{dataset}} of Node: {{hostname}}"
    }
   ]
  },
  {
   "title": "Rate of Unlinks",
   "type": "timeseries",
   "description": "Rate of Unlinks",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_dataset_nunlinks{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{dataset}} of Node: {{hostname}}"
    }
   ]
  },
  {
   "title": "Dataset Write Operations Rate",
   "type": "timeseries",
   "description": "Dataset Write Operations Rate",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_dataset_writes{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])\r\n",
     "legendFormat": "{{dataset}} of Node: {{hostname}}"
    }
   ]
  },
  {
   "title": "Rate of Nwritten",
   "type": "timeseries",
   "description": "Rate of Nwritten",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 31 },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_dataset_nwritten{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{dataset}} of Node: {{hostname}}"
    }
   ]
  },
  { "title": "ARC", "type": "row", "description": "ARC", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "ARC size",
   "type": "timeseries",
   "description": "ARC size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}} Data Size"
    },
    {
     "expr": "node_zfs_arc_metadata_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}} Metadata Size"
    },
    {
     "expr": "node_zfs_arc_mfu_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}} MFU Size"
    },
    {
     "expr": "node_zfs_arc_dnode_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}} Dnode Size"
    },
    {
     "expr": "node_zfs_arc_mru_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}} MRU size"
    },
    {
     "expr": "node_zfs_arc_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}} ARC Size"
    }
   ]
  },
  {
   "title": "ARC size",
   "type": "stat",
   "description": "ARC size",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC data size",
   "type": "stat",
   "description": "ARC data size",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC metadata size",
   "type": "stat",
   "description": "ARC metadata size",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_metadata_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC Metadata to Total ARC Size Ratio",
   "type": "stat",
   "description": "ARC Metadata to Total ARC Size Ratio",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_metadata_size{luna_group=\"$luna_group\", hostname=\"$hostname\"} / node_zfs_arc_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC Hit Ratio",
   "type": "timeseries",
   "description": "ARC Hit Ratio",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]) / (rate(node_zfs_arc_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]) + rate(node_zfs_arc_misses{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC Hits/Misses",
   "type": "stat",
   "description": "ARC Hits/Misses",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}} hits"
    },
    {
     "expr": "node_zfs_arc_misses{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}} misses"
    }
   ]
  },
  {
   "title": "ARC MRU to MFU Ratio",
   "type": "timeseries",
   "description": "ARC MRU to MFU Ratio",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "node_zfs_arc_mru_size{luna_group=\"$luna_group\", hostname=\"$hostname\"} / node_zfs_arc_mfu_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC MRU size",
   "type": "stat",
   "description": "ARC MRU size",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_mru_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC MFU size",
   "type": "stat",
   "description": "ARC MFU size",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_mfu_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Arc hash collisons",
   "type": "stat",
   "description": "Arc hash collisons",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_hash_collisions{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC Compression Ratio",
   "type": "stat",
   "description": "ARC Compression Ratio",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_compressed_size{luna_group=\"$luna_group\", hostname=\"$hostname\"} / node_zfs_arc_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC Ghost Hits",
   "type": "timeseries",
   "description": "ARC Ghost Hits",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "node_zfs_arc_mru_ghost_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"} + node_zfs_arc_mfu_ghost_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ARC Metadata Efficiency",
   "type": "bargauge",
   "description": "NEEDS REVISION\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(node_zfs_arc_demand_metadata_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]) / (rate(node_zfs_arc_demand_metadata_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]) + rate(node_zfs_arc_demand_metadata_misses{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]))) * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "ABD", "type": "row", "description": "ABD", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "ABD linear data size",
   "type": "stat",
   "description": "ABD linear data size",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_abd_linear_data_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ABD struct size",
   "type": "stat",
   "description": "ABD struct size",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_abd_struct_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ABD Scatter Data Size",
   "type": "stat",
   "description": "ABD Scatter Data Size",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_abd_scatter_data_size{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ABD Scatter Data Size",
   "type": "stat",
   "description": "ABD Scatter Data Size",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_abd_scatter_chunk_waste{luna_group=\"$luna_group\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Dbuf", "type": "row", "description": "Dbuf", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Dbuf Cache Size",
   "type": "stat",
   "description": "Dbuf Cache Size",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_dbuf_cache_size_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Dbuf Cache Count",
   "type": "timeseries",
   "description": "Dbuf Cache Count",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 69 },
   "targets": [
    {
     "expr": "node_zfs_dbuf_cache_count{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Dbuf Cache Total Evictions Rate",
   "type": "timeseries",
   "description": "Dbuf Cache Total Evictions Rate",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 69 },
   "targets": [
    {
     "expr": "rate(node_zfs_dbuf_cache_total_evicts{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Rate of dbuf Hash Collision",
   "type": "timeseries",
   "description": "Rate of dbuf Hash Collision",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(node_zfs_dbuf_hash_collisions{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Dbuf Cache Hit Ratio",
   "type": "timeseries",
   "description": "Dbuf Cache Hit Ratio",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "(rate(node_zfs_dbuf_hash_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]) / (rate(node_zfs_dbuf_hash_hits{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]) + rate(node_zfs_dbuf_hash_misses{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]))) * 100\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "ZIL", "type": "row", "description": "ZIL", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "ZIL Commit Count",
   "type": "stat",
   "description": "ZIL Commit Count",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_zil_zil_commit_count{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ZFS zil itx copied bytes",
   "type": "stat",
   "description": "ZFS zil itx copied bytes",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_zil_zil_itx_copied_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\"}\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ZIL Commit Rate",
   "type": "timeseries",
   "description": "ZIL Commit Rate",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "rate(node_zfs_zil_zil_commit_count{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ZIL Average Commit Size",
   "type": "timeseries",
   "description": "Needs revision\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "rate(node_zfs_zil_zil_itx_copied_bytes{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval]) / rate(node_zfs_zil_zil_commit_count{luna_group=\"$luna_group\", hostname=\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ZIL ITX Needcopy Bytes Rate",
   "type": "timeseries",
   "description": "NEEDS REVISION",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "rate(node_zfs_zil_zil_itx_needcopy_bytes[$__rate_interval])\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}