{
 "title": "High Availability",
 "tags": [
  "HA",
  "system",
  "dashboard"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(up{luna_group=\"controller\"},hostname)"
    }
   },
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Resources and Services",
   "type": "stat",
   "description": "Quick view if all the services are up and running",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max  (ha_cluster_pacemaker_fail_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Floating IP",
   "type": "stat",
   "description": "Hostname of the controller bearing the floating IP",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (node) (ha_cluster_pacemaker_resources{resource=\"trinity-ip\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stonith Fencing",
   "type": "stat",
   "description": "Status of the 'Shoot The Other Node In The Head' feature, allowing to forcefully power off failed nodes, avoiding interferences caused by partial or complex failures",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (ha_cluster_pacemaker_stonith_enabled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Failures",
   "type": "timeseries",
   "description": "Expanded view of failing services",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "max by (resource) (ha_cluster_pacemaker_fail_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources $hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "hostname" },
  {
   "title": "Pacemaker resources",
   "type": "stat",
   "description": "Status of Pacemaker resources on this host",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ha_cluster_pacemaker_resources{node=~\"$hostname\", group!='Trinity-stack'} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pacemaker resources",
   "type": "state-timeline",
   "description": "Status of Pacemaker resources on this host",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "ha_cluster_pacemaker_resources{node=~\"$hostname\", group!='Trinity-stack'} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pacemaker Trinity-stack  resources",
   "type": "stat",
   "description": "Status of Pacemaker Trinity-stack resources on this host",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ha_cluster_pacemaker_resources{node=~\"$hostname\", group='Trinity-stack'} != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pacemaker Trinity-stack resources",
   "type": "state-timeline",
   "description": "Status of Pacemaker  Trinity-stack resources on this host",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "ha_cluster_pacemaker_resources{node=~\"$hostname\", group=\"Trinity-stack\"} != 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}