{
 "title": "Thermals and Power",
 "tags": [
  "thermals",
  "fans",
  "power"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(ipmi_up,hostname)" } }
  ]
 },
 "panels": [
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_chassis_power_state{hostname=\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Sensors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_up{hostname=\"$host\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "IPMI Sensors State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ipmi_sensor_state{hostname=\"$host\"}"
    }
   ]
  },
  {
   "title": "Machine Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ipmi_bmc_info{hostname=\"$host\"}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "host_power" },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_state{hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Consumption watts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(ipmi_dcmi_power_consumption_watts{hostname=\"$host\"}) - sum(nvidia_smi_power_draw_watts{hostname=\"$host\"})",
     "legendFormat": "system"
    },
    {
     "expr": "nvidia_smi_power_draw_watts{hostname=\"$host\"}",
     "legendFormat": "gpu"
    }
   ]
  },
  {
   "title": "Power reading in Watts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{hostname=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "IPMI Temperatures",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{hostname=\"$host\", name=~\".*[tT][eE][mM]?[pP].*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_temperature_state{hostname=\"$host\", name=~\".*[tT][eE][mM]?[pP].*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPMI Fan Speeds",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{hostname=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_fan_speed_state{hostname=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPMI Voltages",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{hostname=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ipmi_voltage_state{hostname=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperatures",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{hostname=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Fans",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{hostname=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}