---
# tasks file for bind

- name: Install bind packages
  yum:
    name: "{{ bind_packages }}"
    state: present
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"
  tags: install-only

- block:
  - name: Selinux fcontext on files
    sefcontext:
      target: "{{ bind_db_path }}(/.*)?"
      setype: named_zone_t

  - name: Selinux permissions for {{ bind_db_path }}/data
    sefcontext:
      target: "{{ bind_db_path }}/data(/.*)?"
      setype: named_cache_t

  - name: Selinux  permissions for {{ bind_db_path }}/dynamic
    sefcontext:
      target: "{{ bind_db_path }}/dynamic(/.*)?"
      setype: named_cache_t
  when: ansible_selinux.status == "enabled"

- name: Ensure {{ bind_db_path }} exists
  file:
    path: "{{ item }}"
    owner: root
    group: named
    setype: named_zone_t
    state: directory
  with_items:
    - "{{ bind_db_path }}"

- name: Ensure {{ bind_db_path }} data directories exists
  file:
    path: "{{ item }}"
    owner: named
    group: named
    setype: named_cache_t
    state: directory
  with_items:
    - "{{ bind_db_path }}/data"
    - "{{ bind_db_path }}/dynamic"

- name: Update named data path
  replace:
    path: /etc/named.conf
    regexp: "/var/named"
    replace: "{{ bind_db_path }}"
    backup: "yes"
  notify: restart named

- name: Configure named to listen on all ports
  replace:
    path: /etc/named.conf
    regexp: "{{ item }}"
    replace: " any; "
  with_items:
    - ' localhost; '
    - ' 127\.0\.0\.1; '
    - ' ::1; '
  notify: restart named

- name: Enable named service
  service:
    name: named
    enabled: "yes"

- block:
  - name: Copy default zones to {{ bind_db_path }}
    synchronize:
      src: /var/named/
      dest: "{{ bind_db_path }}"
  #  creates: "{{ bind_db_path }}/named.empty"
  # - name: Copy default zones to {{ bind_db_path }}
  #  shell: rsync -raW -AX /var/named/* {{ bind_db_path }}
  #  args:
  #    creates: "{{ bind_db_path }}/named.empty"

  - name: Start named service
    service:
      name: named
      state: started

#  when: primary | default(True)
