---

- block:
  - name: Verify if Luna doesn't use standard insecure password
    fail:
      msg: "Luna password is default, it should not be 'luna'. A change in all.yml requires to re-run all playbooks. We warn but continue running...."
    ignore_errors: true

  - name: Wait 10s before we continue
    wait_for:
      timeout: 10
  when:
    - luna_password == 'luna'
    - playbook_done_prior | default(False)

- name: Verify if Luna doesn't use standard insecure password
  fail:
    msg: "Luna password is default, it cannot be 'luna'. Please change this in all.yml to one of your liking and rerun the playbook"
  ignore_errors: "{{ skip_password_check | default(False) }}"
  when:
    - luna_password == 'luna'
    - not playbook_done_prior | default(False)

