---

- name: Verify if Luna doesn't use standard insecure password
  fail:
    msg: "Luna password is default, it cannot be 'luna'. Please change this to one of your liking and rerun the playbook"
  ignore_errors: "{{ skip_password_check | default(False) }}"
  when: luna_password == 'luna'

