---

- name: Copy resolv.sh script to {{ trix_tmpdir }}
  copy:
    src: 'resolve.sh'
    dest: '{{ trix_tmpdir }}/resolve.sh'
    mode: 0755

- name: Resolving trix_external_fqdn
  command: "{{ trix_tmpdir }}/resolve.sh {{ trix_ctrl_external_ip }} {{ trix_dns_forwarders | default([]) | first }}"
  register: trix_resolved_host_fqdn
  ignore_errors: true
  when: trix_ctrl_external_ip is defined

- name: Setting trix_external_fqdn
  set_fact:
    trix_external_fqdn: "{{ trix_resolved_host_fqdn.stdout }}"
  when:
    - (trix_external_fqdn is not defined) or trix_external_fqdn==""
    - trix_resolved_host_fqdn is defined

- fail: 
    msg: 'trix_external_fqdn is not configured and it could not be resolved. OpenOndemand will not work properly. This check can be skipped by "-e skip_fqdn=true"'
  ignore_errors: "{{ skip_fqdn | default(False) }}"
  when: enable_ood

- name: Setting trix_external_fqdn
  set_fact:
    trix_external_fqdn: '{{ ansible_fqdn }}'
  ignore_errors: true
  when: (trix_external_fqdn is not defined) or trix_external_fqdn==""
