# TrinityX environment file
# Do not modify!

TRIX_ROOT=\"$TRIX_ROOT\"
TRIX_VERSION=\"${STDCFG_TRIX_VERSION:-$(git describe --tags)}\"

TRIX_HOME=\"$TRIX_HOME\"
TRIX_IMAGES=\"$TRIX_IMAGES\"
TRIX_LOCAL=\"$TRIX_LOCAL\"
TRIX_LOCAL_APPS=\"$TRIX_LOCAL_APPS\"
TRIX_LOCAL_MODFILES=\"$TRIX_LOCAL_MODFILES\"
TRIX_SHARED=\"$TRIX_SHARED\"
TRIX_SHARED_TMP=\"$TRIX_SHARED_TMP\"
TRIX_SHARED_APPS=\"$TRIX_SHARED_APPS\"
TRIX_SHARED_MODFILES=\"$TRIX_SHARED_MODFILES\"

TRIX_SHADOW=\"/etc/trinity.shadow\"
TRIX_SHFILE=\"/etc/trinity.sh\"
TRIX_LOCAL_SHFILE=\"/etc/trinity.local.sh\"

TRIX_DOMAIN=\"$TRIX_DOMAIN\"
TRIX_CTRL1_HOSTNAME=\"$TRIX_CTRL1_HOSTNAME\"
TRIX_CTRL1_IP=\"$TRIX_CTRL1_IP\"
TRIX_CTRL2_HOSTNAME=\"$TRIX_CTRL2_HOSTNAME\"
TRIX_CTRL2_IP=\"$TRIX_CTRL2_IP\"
TRIX_CTRL_HOSTNAME=\"$TRIX_CTRL_HOSTNAME\"
TRIX_CTRL_IP=\"$TRIX_CTRL_IP\"
