#!/bin/bash

#SBATCH -t 00:30:00
#SBATCH --ntasks=1
#SBATCH -J 'Stage-in'

#check to see if datadir is set from the submitstaged script is set hurl some abuse if not and fail
if [ -z $jobdir ]; then
    echo "jobdir variable NOT SET failing job" >&2
    exit 1
fi

export scratchdir={{ aws.sharedfs_mountpoint }}/$SLURM_JOBID
concurrentjobs=$(sacctmgr show qos data format=GrpJobs -nP)

echo "concurrentjobs = $concurrentjobs"
if [ "$concurrentjobs" -ge 1 ]; then
    speedlimit=$(echo "102400/$concurrentjobs"|bc)
    echo "rsync speed limit is set to $speedlimit"
fi

echo "id: $(id)"
echo "rsync -a --bwlimit=$speedlimit  $jobdir/* $scratchdir/"
rsync -a --bwlimit=$speedlimit  $jobdir/* $scratchdir/
