#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 (jobscript to submit) [job run dir if NOT .]"
    exit 0
fi

if [ -z $2 ]; then
    if [ "$PWD" = "$HOME" ]; then
        echo "You did not specify a dedicated Job run directory and you are submitting from your home Directory."
        echo "This will result in migrating your entire home dir onto the SSD storage which is not an efficient use of space."
        echo "Create a dedicated job directory and specifiy it on the command line according to:"
        ($0)
        exit 1
    fi

    export jobdir=$PWD
    echo "creating jobs to migrate $jobdir to the cloud, run the job with all writes to this folder being redirected to the cloud and then move the data back to disk"
fi

jid=$(sbatch --partition=datajobs --qos=data stage-in)
echo $jid
jid1=${jid/Submitted batch job /}
export scratchdir={{ aws.sharedfs_mountpoint }}/$jid1
jid=$(sbatch --dependency=afterok:$jid1 $1)
echo $jid
jid2=${jid/Submitted batch job /}
sbatch --partition=datajobs --qos=data --dependency=afterany:$jid2 stage-out

