{
 "title": "TrinityX Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "trinityfs",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE path =~ /\\/trinity/"
   }
  ]
 },
 "panels": [
  { "title": "System status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "content": "<img src=\"/public/triX_7.png\" width=\"200\" height=\"200\"/>"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 1 },
   "content": "The webportal for users is available on port 8080.\n\n"
  },
  { "title": "Current Alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 7, "x": 10, "y": 1 } },
  { "title": "Available dashboards", "type": "dashlist", "gridPos": { "h": 11, "w": 7, "x": 17, "y": 1 } },
  {
   "title": "Available cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT sum(\"last\") FROM (SELECT last(\"n_cpus\") FROM \"system\" GROUP BY \"host\" ORDER BY time LIMIT 1)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT sum(\"last\") FROM (SELECT last(\"total\") FROM \"mem\" GROUP BY \"host\" ORDER BY time LIMIT 1)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NFS and other (non-local) filesystems",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "used %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "=", "value": "nfs4" }
     ]
    }
   ]
  },
  {
   "title": "Available nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       { "params": [ "load15" ], "type": "alias" }
      ],
      [
       { "params": [ "n_cpus" ], "type": "field" },
       { "params": [ "cores" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       { "params": [ "total memory" ], "type": "alias" }
      ],
      [
       { "params": [ "available" ], "type": "field" },
       { "params": [ "available memory" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ "used swap" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Trinity Filesystems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$trinityfs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "repeat": "trinityfs",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_path $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^$trinityfs$/" }
     ]
    }
   ]
  }
 ]
}