---
# has to be here for image reasons. not all have pcs_resource available - compile errors
#
- name: Add slurm pacemaker resources
  pcs_resource:
    name: '{{ item }}'
    resource_class: 'systemd'
    resource_type: 'systemd:{{ item }}'
    options: 'meta migration-threshold=3 failure-timeout=120s op monitor interval=30 --group Trinity-stack'
    state: present
  with_items:
    - slurmdbd
    - slurmctld
  tags: pcs

