#!/bin/bash

function check_service {
    for i in $@; do
        echo -ne "   ${i}: "
        systemctl status $i | grep Active | cut -c 12- | awk '
            {
                gsub(/\Active/, "status");
                gsub(/\<active/, "\033[1;32m&\033[0m");
                gsub(/\<inactive/, "\033[1;31m&\033[0m");
                print
            }'
    done
    echo -e "\n"

}

echo -e '\n'

echo "Trinity Core"
check_service chronyd named dhcpd mariadb nfs-server nginx conman

echo "Luna"
check_service mongod lweb ltorrent

echo "LDAP"
check_service slapd sssd nslcd

echo "Slurm"
check_service slurmctld

echo "Zabbix"
check_service zabbix-server
