---
# vars file for cv_support

trix_tools:
  - 'slurmibtopology.sh'
  - 'remote-assistance.sh'

cv_support_packages:
  - tigervnc-server
  - firefox
  - icedtea-web
  - icewm

cv_support_pip_packages: []

project_id: '000000'
trix_version: '0'
ha: 'False'
trix_ctrl_ip: '127.0.0.1'
