---

ood_rpms:
  - name: ["httpd", "@nodejs:20", "@ruby:3.3", "ondemand", "luna2-python"]

ood_repositories:
  - name: ondemand-web
    repo: https://{{ ag_server }}/repos/ondemand-web
    gpgcheck: False
