---
# EL9.5 and newer offer nodejs 22 and ruby 3.3.
ood_release: '4.1'

ood_packages:
  - name: "{{ ['httpd'] + ood_release_runtimes[ood_release] + ['ondemand', 'luna2-python'] }}"

ood_repositories:
  - name: ondemand-web
    repo: https://{{ ag_server }}/{{ ag_repo }}/repos/ondemand-web
    gpgcheck: False
