---
# EL8.7-8.9 offer ruby 3.1 at most, which no OnDemand 4.x can use.
ood_release: '3.1'

ood_packages:
  - name: "{{ ['httpd'] + ood_release_runtimes[ood_release] + ['ondemand', 'luna2-python'] }}"

ood_repositories:
  - name: ondemand-web
    repo: https://{{ ag_server }}/{{ ag_repo }}/repos/ondemand-web
    gpgcheck: False
