---

ood_rpms:
  - name: ["nodejs", "ruby", "ruby-libs", "ondemand", "luna2-python"]

ood_repositories:
  - name: ondemand-web
    repo: https://{{ ag_server }}/{{ ag_repo }}/repos/ondemand-web
    gpgcheck: False
