---
prometheus_server_binary_url: "https://{{ ag_server }}/{{ ag_repo }}/trinityx/{{ _prometheus_server_repo }}/releases/download/v{{ prometheus_server_version }}/\
                        prometheus-{{ prometheus_server_version }}.linux-{{ go_arch }}.tar.gz"
prometheus_server_checksums_url:
