---
prometheus_alertmanager_binary_url: "https://{{ ag_server }}/trinityx/{{ _prometheus_alertmanager_repo }}/releases/download/v{{ prometheus_alertmanager_version }}/\
                          alertmanager-{{ prometheus_alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
prometheus_alertmanager_checksums_url:

prometheus_alertmanager_bcrypt_binary_url: "https://{{ ag_server }}/trinityx/external/monitoring/bcrypt-tool/{{system_arch}}/binaries/{{trix_stream}}/bcrypt-tool.{{prometheus_alertmanager_bcrypt_version}}"
