---

- name: Set MariaDB's root pasword
  ansible.mysql.mysql_user:
    login_user: root
    login_password: ""
    name: root
    password: '{{ mysql_root_pwd }}'
    host_all: true
    check_implicit_admin: true
    state: present
  failed_when: false

- name: Set MariaDB's root pasword
  ansible.mysql.mysql_user:
    config_file: '/root/.my.cnf'
    name: root
    password: '{{ mysql_root_pwd }}'
    host_all: true
    check_implicit_admin: true
    state: present

- name: Remove anonymous users
  ansible.mysql.mysql_user:
    config_file: '/root/.my.cnf'
    name: ''
    host_all: true
    state: absent

- name: Remove test db
  ansible.mysql.mysql_db:
    config_file: '/root/.my.cnf'
    name: test
    state: absent
