---

ood_debs:
  - key_url: https://apt.osc.edu/ondemand/DEB-GPG-KEY-ondemand
    key_id: 4B72FE2B92D31755
  - key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    key_id: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4

ood_deb_repos:
  - deb: "https://apt.osc.edu/ondemand/4.1/ondemand-release-web_4.1.0-{{ ansible_distribution_release }}_all.deb"

ood_packages:
  - name: ["apache2", "nginx", "ondemand"]

ood_dex_packages:
  - name: ondemand-dex

ood_pam_packages:
  - name: libapache2-mod-authnz-pam

ood_user: 'www-data'
ood_apache_service_name: 'apache2'
ood_apache_modules_path: '/etc/apache2/mods-enabled'
ood_htcacheclean_service_name: 'apache2'
