---

ood_rpms:
  - name: epel-release
  - name: https://yum.osc.edu/ondemand/4.1/ondemand-release-web-4.1-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    no_gpgcheck: true
  - name: ["nodejs", "ruby", "ruby-libs", "ondemand", "luna2-python"]

