---

ood_rpms:
  - name: epel-release
  - name: https://yum.osc.edu/ondemand/4.0/ondemand-release-web-4.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    no_gpgcheck: true
  - name: ["@nodejs:20", "@ruby:3.3", "ondemand", "luna2-python"]

