---
# EL9.4 has ruby 3.3 but no nodejs 22.
ood_release: '4.0'

ood_packages:
  - name: epel-release
  - name: https://yum.osc.edu/ondemand/4.0/ondemand-release-web-4.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    no_gpgcheck: true
  - name: "{{ ['httpd'] + ood_release_runtimes[ood_release] + ['ondemand', 'luna2-python'] }}"
