---
# EL8.7-8.9 offer ruby 3.1 at most, which no OnDemand 4.x can use.
ood_release: '3.1'

ood_packages:
  - name: epel-release
  - name: https://yum.osc.edu/ondemand/3.1/ondemand-release-web-3.1-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    no_gpgcheck: true
  - name: "{{ ood_release_runtimes[ood_release] + ['ondemand', 'luna2-python'] }}"
