---
# handlers for the node-console role

- name: restart sol-grab
  systemd:
    name: "{{ sol_grab_service_name }}"
    state: restarted
    daemon_reload: true
  when:
    - on_controller | default(False)
    - sol_grab_enable
