trinityx_pdsh_repo_baseurl: "https://{{ ag_server }}/{{ ag_repo }}/repos"
trinityx_pdsh_arch: "{{ system_arch | default(ansible_architecture) }}"


trinityx_pdsh_repositories:
  - name: RedHat
    repo: "{{ trinityx_pdsh_repo_baseurl }}/cv-pdsh"
    gpgcheck: false