trinityx_pdsh_repo_baseurl: "https://{{ ag_server }}/{{ ag_repo }}/trinityx"
trinityx_pdsh_arch: "{{ system_arch | default(ansible_architecture) }}"


trinityx_pdsh_repositories:
  - name: RedHat
    repo: "{{ trinityx_pdsh_repo_baseurl }}/el/{{ ansible_distribution_major_version }}/{{ trinityx_pdsh_version }}/{{ trinityx_pdsh_arch }}"
    gpgcheck: false