---
# CV-Slurm repositories served from the airgap mirror

trinityx_slurm_repositories:
  - name: RedHat
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/slurm/25.11.5/redhat
    gpgcheck: false
  - name: Ubuntu
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/slurm/25.11.5/ubuntu
    gpgcheck: false
  - name: Debian
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/slurm/25.11.5/ubuntu
    gpgcheck: false
  - name: Suse
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/slurm/25.11.5/suse
    gpgcheck: false
  - name: SLE
    repo: https://{{ ag_server }}/{{ ag_repo }}/trinityx/slurm/25.11.5/suse
    gpgcheck: false
